name: Feature Request
description: Use this template for creating a feature request.
labels: ["Type: Feature"]
assignees:
  - Levminer
body:
- type: checkboxes
  attributes:
    label: Before the feature request.
    description: Please ensure you've completed all of the following.
    options:
      - label: I have searched the [Github Issues](https://www.github.com/levminer/authme/issues) for a feature request that matches the one I want to file, without success.
        required: true
- type: textarea
  attributes:
    label: Your feature request related to the problem
    description: A clear and concise description of what the problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like or alternatives you've considered
    description: A clear and concise description of what you want to happen and any alternative solutions you've considered..
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional information
    description: If your problem needs further explanation, please add more information here.
