name: Alpha Artifacts
on:
    push:
        branches: [dev]
jobs:
    build:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                include:
                    - os: macos-latest
                      NAME: mac
                    - os: ubuntu-latest
                      NAME: linux
                    - os: windows-latest
                      NAME: windows
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '15'
            - name: Install modules
              run: npm ci
            - name: Run build
              run: npm run build:alpha
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: authme-latest-alpha-${{matrix.NAME}}-x64-installer-portable
                  path: dist
            - name: Get build file
              uses: actions/upload-artifact@v2
              with:
                  name: build-${{matrix.NAME}}.json
                  path: dist/build.json
