name: Mac Artifacts

on:
    push:
        branches: [dev]

jobs:
    archive-build-artifacts:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install modules
              run: npm i

            - name: Run Build
              run: npm run build

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: authme-latest-mac-x64-installer-portable
                  path: dist
