name: Test
on: push
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: npm ci
            - name: Run Test
              run: npm run test
